package project11002;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Product_Search extends javax.swing.JFrame {

    /**
     * Creates new form Product_Search
     */
   public Connection con;
    PreparedStatement pst;
    public Product_Search() {
        initComponents();
        connect();
    }
    public void connect()
    {
        String connection = "jdbc:sqlserver://localhost:1433; databaseName=Project1799 ;user=sa;password=123456"  ;
        try {
            con=DriverManager.getConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ss = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setText("Product-Req peoduct More Info");

        jComboBox1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product Pricing", "Requested Customer Info", "Requested Product Billing", "InStock", "Soon Out of Stock", " " }));

        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(138, 138, 138))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Mainpage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("Product Pricing"))
        {
            try {
                if(ss.getText().isEmpty())
                {
                    String qe ="select i.pro_name,i.pro_brand,p.pro_price,p.pro_sellingPrice from product_info i right join product p on i.pro_id=p.pro_id ";
                    pst =con.prepareStatement(qe);  
                  //  pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else{
                    String qe ="select i.pro_name,i.pro_brand,p.pro_price,p.pro_sellingPrice from product_info i right join product p on i.pro_id=p.pro_id where pro_name=? ";
                    pst =con.prepareStatement(qe);  
                   pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Product_Search.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jComboBox1.getSelectedItem().equals("Requested Customer Info"))
        {
           try {
                if(ss.getText().isEmpty())
                {
                    String qe ="select i.pro_name,r.cus_name,r.cus_phone from product_info i right join req_product r on i.pro_id=r.req_pro_id";
                    pst =con.prepareStatement(qe);  
                  //  pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else{
                    String qe ="  select i.pro_name,r.cus_name,r.cus_phone from product_info i right join req_product r on i.pro_id=r.req_pro_id where pro_name=? ";
                    pst =con.prepareStatement(qe);  
                   pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Product_Search.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else if(jComboBox1.getSelectedItem().equals("Requested Product Billing"))
        {
            try {
                if(ss.getText().isEmpty())
                {
                    String qe =" select i.pro_name,i.pro_brand,r.advance_payment,r.due_payment from product_info i right join req_product r on i.pro_id=r.req_pro_id";
                    pst =con.prepareStatement(qe);  
                  //  pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else{
                    String qe =" select i.pro_name,i.pro_brand,r.advance_payment,r.due_payment from product_info i right join req_product r on i.pro_id=r.req_pro_id where pro_name=? ";
                    pst =con.prepareStatement(qe);  
                   pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Product_Search.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        else if(jComboBox1.getSelectedItem().equals("InStock"))
        {
            try {
                if(ss.getText().isEmpty())
                {
                    String qe =" select i.pro_name,i.pro_brand,p.pro_quantity from product_info i right join product p on i.pro_id=p.pro_id";
                    pst =con.prepareStatement(qe);  
                  //  pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                else{
                    String qe =" select i.pro_name,i.pro_brand,p.pro_quantity from product_info i right join product p on i.pro_id=p.pro_id where pro_name=? ";
                    pst =con.prepareStatement(qe);  
                   pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Product_Search.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else
        {
            try {
               
                    String qe =" select i.pro_name,i.pro_brand,p.pro_quantity from product_info i right join product p on i.pro_id=p.pro_id where p.pro_quantity<5";
                    pst =con.prepareStatement(qe);  
                  //  pst.setString(1,ss.getText());
                    ResultSet rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
               
                
            } catch (SQLException ex) {
                Logger.getLogger(Product_Search.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
       

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ss;
    // End of variables declaration//GEN-END:variables
}
