/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project11002;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class Supplier_Transaction_more_info extends javax.swing.JFrame {

    /**
     * Creates new form adminMoreSearch
     */
    public Connection con;
    PreparedStatement pst;
    public Supplier_Transaction_more_info() {
        initComponents();
        connect();
    }
    public void connect()
    {
        String connection = "jdbc:sqlserver://localhost:1433; databaseName=Project1799 ;user=sa;password=123456"  ;
        try {
            con=DriverManager.getConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ss = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jComboBox1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All supplier info", "Search by supplier id", "search by transaction id", "How many transactions with suppliers in a certain date", "Full supplier and transaction table", "Max Price(by producttype)", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setText("Supplier-Transaction More Info");

        jButton2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedItem().equals("All supplier info"))
        {
            try {
                String qe ="select supplier_info.supplier_id,suppplier_name\n" +
                            ",transactions.tran_id,Total_amount,tran_date ,supplier.pro_quantity,pro_Stock,pro_dop,pro_doe,pro_purchasePrice from supplier_info\n" +
                            "inner join Transactions on supplier_info.supplier_id = Transactions.supplier_id\n" +
                            "inner join supplier on transactions.supplier_id = supplier.supplier_id ";
                pst =con.prepareStatement(qe);
                //pst.setString(1,ss.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                //pst.close();

            } catch (SQLException ex) {
                Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jComboBox1.getSelectedItem().equals("Search by supplier id"))
                {
                    try {
                        String qe ="select supplier_info.supplier_id,suppplier_name\n" +
",transactions.tran_id,Total_amount,tran_date ,supplier.pro_quantity,pro_Stock,pro_dop,pro_doe,pro_purchasePrice from supplier_info\n" +
"inner join Transactions on supplier_info.supplier_id = Transactions.supplier_id\n" +
"inner join supplier on transactions.supplier_id = supplier.supplier_id where supplier.supplier_id = ?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("search by transaction id"))
                {
                    try {
                        String qe ="select supplier_info.supplier_id,suppplier_name\n" +
",transactions.tran_id,Total_amount,tran_date ,supplier.pro_quantity,pro_Stock,pro_dop,pro_doe,pro_purchasePrice from supplier_info\n" +
"inner join Transactions on supplier_info.supplier_id = Transactions.supplier_id \n" +
"inner join supplier on transactions.tran_id=? ";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("How many transactions with suppliers in a certain date"))
                {
                    try {
                        String qe ="  select count(supplier_info.supplier_id) as supplier_id_count\n" +
",Transactions.tran_date,SUM(Total_amount) as total_amount from supplier_info\n" +
"  inner join Transactions on supplier_info.supplier_id =  Transactions.Supplier_id group by Transactions.tran_date having tran_date = ?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         
         else if(jComboBox1.getSelectedItem().equals("Full supplier and transaction table"))
                {
                    try {
                        String qe ="select supplier_info.supplier_id,suppplier_name\n" +
",transactions.tran_id,Total_amount,tran_date,amount_paid,[amount due] from supplier_info\n" +
"left join Transactions on supplier_info.supplier_id = Transactions.supplier_id\n" +
"union \n" +
"select supplier_info.supplier_id,suppplier_name\n" +
",transactions.tran_id,Total_amount,tran_date,amount_paid,[amount due] from supplier_info\n" +
"right join Transactions on supplier_info.supplier_id = Transactions.supplier_id\n" +
"";
                        pst =con.prepareStatement(qe);
                       // pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
          else if(jComboBox1.getSelectedItem().equals("Max Price(by producttype)"))
                {
                    try {
                        String qe =" SELECT  max(pro_purchasePrice)as maxprice ,supplied_prod_type FROM supplier join supplier_info \n" +
" on supplier.supplier_id = supplier_info.supplier_id GROUP BY supplied_prod_type having supplied_prod_type =? ";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Mainpage f =new Mainpage();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_Transaction_more_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_Transaction_more_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_Transaction_more_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_Transaction_more_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_Transaction_more_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ss;
    // End of variables declaration//GEN-END:variables
}
