/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project11002;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class BranchManSearch extends javax.swing.JFrame {

    /**
     * Creates new form adminMoreSearch
     */
    public Connection con;
    PreparedStatement pst;
    public BranchManSearch() {
        initComponents();
        connect();
    }
    public void connect()
    {
        String connection = "jdbc:sqlserver://localhost:1433; databaseName=Project1799 ;user=sa;password=123456"  ;
        try {
            con=DriverManager.getConnection(connection);
        } catch (SQLException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        ss = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jComboBox1.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager basic info", "Manager Salary", "joining date & status", "sell_reports before date ", "sell_reports after date ", "Max Salary", "Min Salary", "Salary>", "Salary<" }));

        jButton1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setText("Branch Manager More Info");

        jButton2.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(171, 171, 171))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedItem().equals("Manager basic info"))
        {
            try {
                String qe ="SELECT bran_manager.br_mn_id,employee1.emp_name ,emp_name, emp_age,emp_address FROM employee1 INNER JOIN bran_manager  ON employee1.emp_id = bran_manager.emp_id where br_mn_id =?";
                pst =con.prepareStatement(qe);
                pst.setString(1,ss.getText());
                ResultSet rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                //pst.close();

            } catch (SQLException ex) {
                Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jComboBox1.getSelectedItem().equals("Manager Salary"))
                {
                    try {
                        String qe ="SELECT bran_manager.br_mn_id,employee1.emp_salary FROM employee1 INNER JOIN bran_manager  ON employee1.emp_id = bran_manager.emp_id where br_mn_id =?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("joining date & status"))
                {
                    try {
                        String qe ="SELECT bran_manager.br_mn_id,employee1.emp_join_date,status FROM employee1 INNER JOIN bran_manager  ON employee1.emp_id = bran_manager.emp_id where br_mn_id =?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("sell_reports before date "))
                {
                    try {
                        String qe ="SELECT bran_manager.br_mn_id,emp_id,Sell_report_2.weekly_expense,weekly_revenue,report_date FROM  bran_manager INNER JOIN Sell_report_2  \n" +"ON bran_manager.br_mn_id = Sell_report_2.br_mn_id where report_date <?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         
         else if(jComboBox1.getSelectedItem().equals("sell_reports after date "))
                {
                    try {
                        String qe ="SELECT bran_manager.br_mn_id,emp_id,Sell_report_2.weekly_expense,weekly_revenue,report_date FROM  bran_manager INNER JOIN Sell_report_2  \n" +"ON bran_manager.br_mn_id = Sell_report_2.br_mn_id where report_date >?";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
          else if(jComboBox1.getSelectedItem().equals("Max Salary"))
                {
                    try {
                        String qe ="SELECT emp_position, max(emp_salary) as salary\n" +"FROM employee1\n" +"GROUP BY emp_position";
                        pst =con.prepareStatement(qe);
                        //pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
          else if(jComboBox1.getSelectedItem().equals("Min Salary"))
                {
                    try {
                        String qe ="SELECT emp_position, Min(emp_salary) as salary\n" +"FROM employee1\n" +"GROUP BY emp_position";
                        pst =con.prepareStatement(qe);
                        //pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("Salary>"))
                {
                    try {
                        String qe ="SELECT *\n" +"FROM bran_manager\n" +"WHERE emp_id in (SELECT emp_id\n" +"FROM employee1\n" +"WHERE emp_salary >= ?)";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
         else if(jComboBox1.getSelectedItem().equals("Salary<"))
                {
                    try {
                        String qe ="SELECT *\n" +"FROM bran_manager\n" +"WHERE emp_id in (SELECT emp_id\n" +"FROM employee1\n" +"WHERE emp_salary <= ?)";
                        pst =con.prepareStatement(qe);
                        pst.setString(1,ss.getText());
                        ResultSet rs = pst.executeQuery();
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        //pst.close();

                    } catch (SQLException ex) {
                        Logger.getLogger(admin_table.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Branch_Manager f =new Branch_Manager();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchManSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchManSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchManSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchManSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchManSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ss;
    // End of variables declaration//GEN-END:variables
}
